### ISSUE TITLE
when open emacs , another window display some message .

### ISSUE THREAD

**Issue by bommbo** [benjaminor/kkp#2]
![Screenshot from 2023-03-08 19-32-35](https://user-images.githubusercontent.com/61496351/223702887-2a4690ed-a33b-4d6c-af00-b64865485743.png)

**Comment by benjaminor** [comment]
Hi, it would be great if you could provide more information about your setup:
- Emacs version
- terminal and terminal version
- check if the issues arises with an empty config, i.e., start Emacs with `emacs -Q` and only add kkp

Additionally you can run "C-h l" (view-lossage) after this window opens and provide the output of the buffer that opens.
This way it's easier for me to debug the issue.

**Comment by bommbo** [comment]
# version
GNU Emacs 29.0.60
kitty 0.27.1 
# configuration
(add-to-list 'load-path "xx/kkp-20230301.2147/")
(add-to-list 'load-path "xx/compat-29.1.3.4/")
(require 'kkp)
(global-kkp-mode 1)
# c-h l
 ESC [ ? 0 u ESC [ > 1 ; 4 0 0 0 ; 2 7 c ESC [ ? ;; describe-prefix-bindings
 0                     ;; self-insert-command
 u                     ;; self-insert-command
 ESC [ 1 0 4           ; 5 u l ;; view-lossage

**Comment by benjaminor** [comment]
Thanks for the info, I'll look into it!

**Comment by benjaminor** [comment]
I could reproduce it, at startup `global-kkp-mode` ran too early before tty initialization and interfered with xterm setup.
Fixed by d587e3f8f2ee97cbcd76f8158aa13397d9d89d5f.

Thanks for reporting the issue! Feel free to open again if this fix does not work for you.

**Comment by zhenhua-wang** [comment]
Hi, I found that if I click any keys during emacs initialization, this page would still show up and kkp would fail to work...
